name: mostrar hola 
on:
  push:
    branch: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: escribir hola por la pantalla 
      run: |
        echo "hola es mi primer git action"
        date
        ls
        echo "version de java"
        java -version || echo "java no instalado"        